name: Upload File

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload file to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 将 SSH 私钥添加到环境变量
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # 将 SSH 私钥写入文件
        chmod 600 ~/.ssh/id_rsa  # 设置正确的权限
        scp -i ~/.ssh/id_rsa file:///C:\Users\Home\Downloads\index.html user@your-server-ip:/path/to/remote/directory/

    - name: Commit and push file
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.email "krr163play@gmail.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Upload index.html"
        git push https://github.com/Krr2023/patientnow/ main
