name: Upload File

on:
  push:
    branches:
      - main  # 替换成您的主要分支名称

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy file to repository
      run: |
        cp C:/Users/Home/Downloads/index.html $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Upload index.html"
        git push https://github.com/Krr2023/patientnow/ main
