name: Update num.html

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: index.html
          path: /tmp/index.html

      - name: Extract user number
        run: |
          cat /tmp/index.html | grep -o "userNumber=[0-9]*" | cut -d "=" -f 2
          echo "number=$(cat /tmp/index.html | grep -o "userNumber=[0-9]*" | cut -d "=" -f 2)" >> $GITHUB_ENV

      - name: Generate num.html
        run: |
          echo "<!DOCTYPE html>
          <html lang="zh-TW">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>優植牙醫診所看診進度</title>
          </head>
          <body>
          <h1>優植牙醫診所</h1>
          <h2>王志綱醫師</h2>
          <h3>現在看診號碼</h3>
          <h4>$userNumber</h4>

          <script>
            const numberElement = document.getElementById("number");

            // Display current time (optional)
            const showTime = () => {
              const now = new Date();
              // ... update time display logic ...
              numberElement.textContent = `Now: ${// formatted time}`;
            };

            // Enable time display (uncomment if desired)
            // setInterval(showTime, 1000);
          </script>
          </body>
          </html>" > num.html

      - name: Commit and push changes
        uses: svenstaro/upload-release-action@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: num.html
          tag: ${{ github.sha }}
          prerelease: false

